name: CI Build and Test

on: [push] # The event that triggers the workflow

jobs:
  build: # The job ID
    runs-on: ubuntu-latest # The runner environment

    steps:
    - name: Print current branch
      run: echo "Current ref name is ${{ github.ref_name }}"
    - uses: actions/checkout@v4 # Action to check out your repository code
    - uses: databricks/setup-cli@main
    - name: Validate bundle
      working-directory: ./example
      run: databricks bundle validate
      env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_ACCOUNT_ID: ${{ secrets.DATABRICKS_ACCOUNT_ID }}
    # - name: Deploy bundle
    #   run: databricks bundle deploy -t ${{ github.ref_name }}
