name: CI Build and Test

on: [push] # The event that triggers the workflow

jobs:
  build: # The job ID
    runs-on: ubuntu-latest # The runner environment

    steps:
    - name: Print current branch
      run: echo "Current ref name is ${{ github.ref_name }}"
    - uses: actions/checkout@v4 # Action to check out your repository code
    - uses: databricks/setup-cli@main
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: Validate bundle
      working-directory: ./example
      env:
        DATABRICKS_AUTH_TYPE: pat
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      run: |
        databricks bundle validate
    - name: Deploy bundle
      working-directory: ./example  
      run: databricks bundle deploy -t ${{ github.ref_name }}
      env:
        DATABRICKS_AUTH_TYPE: pat
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
